#+TITLE: WATERSHIP DOWN: AN INDEX
#+OPTIONS: num:nil toc:nil
#+LaTeX_CLASS_OPTIONS: [mathptmx,a4paper,10pt,microtype,paralist,twocolumn]
#+DESCRIPTION: Watership Down index, index to Watership Down, Watership Down glossary
#+AUTHOR: John Tait

#+BEGIN_HTML

<style>body{text-align:center;margin:20px;font-family:consolas,Menlo-Regular,Menlo,Monaco,monospace;font-size:125%;line-height:135%} a {color:blue;text-decoration:none;} .title{font-size:200%;color:crimson;} body{margin:0 auto;text-align:left;max-width:768px;width:100%;padding:10px;box-sizing:border-box,font-size:100%;} @media (max-width: 480px)</style>

#+END_HTML 

*by John Tait*

A supplement to the classic rabbit epic [[https://en.wikipedia.org/wiki/Watership_Down][/Watership Down/]] by the late Richard Adams: a full index to the print version.

Page numbers are from 2014 Puffin edition.

/Watership Down/ is arguably the best book in the whole world. It was the basis for a smash hit 1978 [[https://en.wikipedia.org/wiki/Watership_Down_%28film%29][film]] of the same name.

/Watership Down/ © 1972 Richard Adams.

Comments welcome: [[mailto:johngtait@gmail.com][johngtait@gmail.com]]. Please write and say hello if you like this.

----------
#+BEGIN_CENTER
This is a work in progress. It isn't finished. Up to p.169.
#+END_CENTER

----------------

#+BEGIN_VERSE
*A*
/A Woman Young and Old/, 34
Acorn, introduction to, 24
Aeschylus, 3
/Agamemnom/, 3
Auden, W.H., 139

*B*
badger (/lendri/), 39--42
beanfield, 57--88
behaviour /see/ rabbit
 behaviour
Betony, first mention of,
 107
Bigwig
   fight, 26--27, 56
   introduction to, 13
   left Owsla, 18
   name in Lapine
    (/Thlayli/), 13
   snare, caught in,
     144--8
   strength, 161
   swimming, 46--47
Blackberry
   introduction to
    (unnamed, rabbit with
    black-tipped ears), 5
   named, 17
   plan to cross Enbourne,
    48--50
   wits, 161
blackbird song, 43
Blake, William, 159
Bonaparte, Napoleon, 39
Browning, Robert, 52
Buckthorn
   bitten by rats, 160
   fight, 26--27
   introduction to, 24
Bunyan, John, 59
burnet leaf, 20
Butler, Matthew:
#+END_VERSE
#+BEGIN_HTML
<center>
<iframe width="640" height="360" src="https://www.youtube.com/embed/elkCXVp_BqU" frameborder="0" allowfullscreen></iframe>
</center>
#+END_HTML
#+BEGIN_VERSE
*C*
Capt. Holly
   fight, 26--27
   first mention, 17
   introduction to, 26
carrots
   /flayrah/, as, 112
   tasting (Hazel), 113
Chief Rabbit
   Cowslip's Warren, lack of, 99--100
   Sandleford, of
      introduction to, 14
      name in Lapine (/Threarah/), 13
      reluctance to leave Sandleford, 15--6
      response to myxomatosis in Sandleford, 14
   Watership Down, of (Hazel-rah)
      first mention regarding, 76
counting, rabbit concept of, 5
/Cosi fan tutte/, 123
cowslip (flower), 6
Cowslip
   evasive/pretending not to hear, 114--5, 120, 147, 149--150
   first mention of, 82
   introduced himself, 86
   laughter, 106
   rejection of stories, 133--4
   Warren, description of, 95--96, 117
Cottington's Clump, 68
creation, rabbit myth, 34--8
crow
   attack, 55--6
   'Not-hawk', 53

*D*
Dandelion
   fight, 27
   introduction to, 17
   speed, 30, 162
   stories, /see/ stories
/De Gustibus/, 52
de la Mare, Walter, first pages
de Ponte, Lorenzo, 123
doe
   admiration (/Nildro-hain/), 105
dog
   in wood, 47
   Sandleford, Owsla opinion of, 41--2
dog's mercury, 18

*E*
Earl of Chesterfield, the, 105
El-ahrairah
   boasting, 35
   exclamation, as, 92
   first mention of, 30--31
   pronounciation, 30
   stones mystery (Cowslip's Warren), 102--103
   stories, /see/ stories
   wives, 35
/embleer/ (stinking, smell of fox), defined, 46
Enbourne (river)
   crossing, 51--2
   described, 40, 44--5
   plan to cross, 42, 45
/elil/ (enemies), defined, 5
exclamations /see/ sayings, rabbit

*F*
farmer, shooting, 60-1
fight
   crow (Bigwig), 56
   rats (Bigwig, Buckthorn, Silver), 160--1
   Sandleford, departing (Capt. Holly, Bigwig, Buckthorn, Dandelion), 26--27
Fiver
   dream about water, 11--2
   fear and flight, 136--7
   Fiver-rah!, 167
   introduction to, 5
   name in Lapine (/Hrairoo/), 5
   requirements for Watership Down, 45
   visions and premonitions, 7--8, 12, 16, 69, 90, 99, 116--8, 134--8, 151--4, 161
/flayrah/ (appetizing food)
   defined, 112
   first mentioned, 109
force, use of, 138
/Four Postures of Death/, 132
fox
Frith (God, also the sun)
   bestowing El-ahrairah 'Prince with a Thousand Enemies', 35
   blessing El-ahrairah's bottom, 37--8
   introduction to, 34
   poem (Silverweed), 135--6
   presents to the animals, 35--8
   warning El-ahrairah, 35
/fu Inl\eacute/ (after moonrise)
   defined, 20
   first mention, 19

*H*
Hamlet, 21
Hardy, Thomas, 169
Hawkbit
   introduction to, 23
   wants to return to Sandleford, 66--67
   inspecting holes, 167--8
Hazel
   dream, 109, 139--140
   introduction to, 4
   leadership, 41, 47, 71--72, 76, 96, 161
Hazel-rah, first mentions, 75--6
hedgehog
   name in Lapine (/yona/), 64
   Yona (story), 125, 130
/Hlao/ (any small concavity in the grass where moisture may collect)
   defined (name of Pipkin in Lapine), 22
/Hlao-roo/, diminutive form of Pipkin's name, first mentioned, 108
high, lonely place with dry soil (Watership Down), 45
/Hoi, Hoi u embleer Hrair, M' saigon ul\eacute hraka vair/ (Hoi, Hoi, the stinking Thousand, We meet them even when we stop to pass our droppings, Owsla lampoon), defined,
 56
holes on Watership Down, 168--170
Holly (rabbit), /see/ Capt. Holly
/homba/ (fox)
   /see also/ fox
   first mention, 100 
/hrair/ (a lot), defined, 5
/Hrairoo/ Little Thousand (name of Fiver in Lapine), defined, 5
/hraka/ (droppings)
   defined (Owlsa lampoon), 56
   passing, 113
/hrududu/ (motor vehicle), defined, 55

*L*
Labernum (Poison-tree, name of rabbit in Cowslip's Warren)
   /see/ Shape of Laburnum
lark, announcing morning, 42
laughter, unknown to most rabbits, 106
/Le Morte d'Arthur/, 71
/lendri/ (badger), first mention, 40
/Letters to the Sun/, 105
Lockley, R.M., 28, 77

*K*
Kelfazin, marshes /see/ stories
Keyes, Sidney, 132
Kingcup (rabbit), first mentioned (missing, called by Strawberry), 103--4

*M*
Malory, 71
man smell, 109, 147
magpie, 156
martins, 44
movement, rabbit, 31--2
myths
   belief in, 133
   creation, 34--38
   El-ahrairah, Shape (Cowslip's Warren), 102--3, 105
myxomatosis, in Sandleford, 14

*N*
Newtown Common, 65
/ni-Frith/ (noon)
   defined, 12
   used, 46, 82
/Nildro-Hain/ (Song of the Blackbird, name of doe in Cowslip's Warren)
   admired, 105
   introduced, doe of Strawberry, 100
notice board of development of Sandleford, 10, 17

*O*
outskirter (rank-and-file ordinary rabbit), defined, 4
owl, 73
   call, 65--66, 141
/Owsla/ (strong or clever rabbits surrounding the Chief Rabbit)
   defined, 6--7
   lampoon, 56
   story, Rabscuttle, 125
   teaching,
      /hrududil/, 64
      snare, 145--6
    
*P*
poetry (Cowslip's Warren), 134--6
Pipkin
   crossing Enbourne, 49--50, 58
   injury, 32, 40, 46
   introduction to, 22
   name in Lapine (/Hlao/), 22
   screaming, 54
"Piss off!", 239
Prince with a Thousand Enemies
   called by Prince Rainbow, 126
   Frith bestows El-ahrairah, 38
Prince Rainbow /see/ stories

*R*
rabbit behaviour
   digging, 81--82, 147--8
   carrying food, 114--5
   cleaning wounds, 58, 72
   conventions and formalities, 98--9
   counting, rabbit concept of, 5
   dancing (Cowslips's Warren), 94
   disgust, 64
   fear and flight (/see also tharn/), 136--7
   fools, teaching about, 90
   force, use of, 138, 141 (discussed)
   formal gestures (usual lack of), 94
   laughter, unknown to most rabbits, 106
   melancholy, unknown to most rabbits, 132
   movement, 31--3, 164
   senses, underground, 96
   screaming, 5
   smelling, 88
   sniffing during greeting, 83--4, 94
   stamping, 82, 109--110
   swimming, 42
   unknown, response to, 29
   time, rabbit concept of, 21, 59
   woodland, in, 28
rabbit feet, 58
rat attack, 160--1
river /see/ Enbourne
road, crossing, 62--3
/-roo/, little (name suffix), defined, 5

*S*
sainfoin, 162--3
Sandleford
   development of, 10
   first mention of, 7
   myxomatosis in, 14
   plan to leave, 19
"/Sayn lay narn, marli?/" ("Is grounsel nice, mother?", muttered by Pipkin in sleep), 109
sayings, rabbit
   By the King's Lettuce!, 141
   Fits like a bee in a foxglove, 154
   For El-ahrairah to cry, 151
   Frith above!, 58
   Frith and Inl\eacute, 50
   Frith forbid!, 155
   Frith in a fog!, 72
   /Frithrah!/ (Lord God!), 19
   Hills or Inl\eacute, 150
   If you were a horse the ceiling would fall down, 110
   In the warren, more stories than passages, 121
   My heart has joined the Thousand, for my friend stopped running today, 149
   /O embleer Frith!/ (Fiver's impiety, O stinking God!), 151
   O Frith, 166
   O Frith on the hills!, 166--7
Shakespeare, 21
Shape of Laburnum, 102--3, 105, 133
/silf/ (outside), first mention of, 140
/silflay/ (go above ground to feed), first mention of, 106
Silver, introduction to, 25
Silverweed (rabbit poet in Cowslip's Warren), 134--6
snake, 65
snare, 119, 144--8
Speedwell
   introduction to, 24
Starveall (lonely barn), 160
stones /see/ Shape of Laburnum
stories
   /see also/ myths
   Dandelion telling, 33, 122, 132
   El-ahrairah and the pike, 31
   Kelfazin, marshes, 123
   King Darzin
      first mentioned, 124
   Prince Rainbow
      first mentioned, 123
   /The Story of the Blessing of El-ahrairah/, 34--38
   /The Story of the King's Lettuce/
      as expression, 141
      mentioned in Cowslip's Warren, 102--3
      told, 123--131
   Rabscuttle, Captain of Owsla
      first mentioned, 125
   Yona the hedgehog, 125, 130
Strawberry
    Hazel admires, 110
    introduction to, 100
    leaves Cowslip's Warren, 155--6
    struggles, 162
    tells stones (Shape of Laburnum) mystery, 101--3
swearing
    for Frith's sake, 91
    /O embleer Frith!/, 151
    Piss off!, 239
swimming
   Bigwig, 46--7
   rabbit ability, 42

*T*
Tennyson, 93
/The Acts of the Apostles/, 44
/The Anabasis/, 17
/The Lotus Eaters/, 93
/The Marriage of Heaven and Hell/, 159
/The Pilgrim's Progress/, 59
/The Private Life of the Rabbit/, 28, 77
/The Witness/, 139
/The World/, 11
/tharn/ (paralysis caused by fear and exhaustion)
   defined, 32
   further explained, 164--5
/Thlayli/ (Furhead, name of Bigwig in Lapine), defined, 13
/Threarah/ (Lord Rowan Tree, name of Chief Rabbit of Sandleford in Lapine), defined, 13
Thousand, dog member of, 42
time, rabbit concept of, 21, 59
Toadflax, introduction to, 6
trees in November, like (Pipkin, Cowslip Warren rabbits), 107

*U*
/U Hrair/, The Thousand ('All the enemies' in Lapine), defined, 5
unknown, rabbit behaviour is reponse to, 29

*V*
Vaughan, Henry, 11

*W*
warren, description of old warren, 88
Watership Down
   description, 68, 74, 159--160, 166
   Fiver's requirements, 45, 68, 163
/Who's in the Next Room?/, 169
woods, 28--33

*X*
Xenophon, 17

*Y*
Yeats, W.B., 34
/yona/ (hedgehog), 64
Yona the hedgehog (story), 125, 130
#+END_VERSE 




